### ISSUE TITLE
Bug in geoscript.layer.Pyramid

### ISSUE THREAD

**Issue by sbortman** [geoscript/geoscript-groovy#14]
When setting the initial projection on line 19:

    Bounds bounds = new Bounds(-179.99, 179.99, -90, 90, "EPSG:4326")

Shouldn't that be:

    Bounds bounds = new Bounds(-179.99, -90, 179.99, 90, "EPSG:4326")

?

**Comment by jericks** [comment]
Yep, thats a bug.  I will fix is shortly.  Good catch!
