### ISSUE TITLE
Grid size attribute exceeding precision

### ISSUE THREAD

**Issue by gpotts** [geoscript/geoscript-groovy#15]
The size attribute is exceeding precision due to the fact that it is calculated with width*height.  Both width and height are integers and are blowing up at around level 16 for a geographic quad split.  Changing the constructor and the attributes of width and height will fix this issue.

class Grid {

    /**
     * The zoom level
     */
    long z

    /**
     * The width or number of columns
     */
    long width

    /**
     * The height or number of rows
     */
    long height

    /**
     * The number of tiles
     */
    long size

    /**
     * The x resolution
     */
    double xResolution

    /**
     * The y resolution
     */
    double yResolution

    /**
     * Create a new Grid
     * @param z The zoom level
     * @param width The width or number of columns
     * @param height The height or number of rows
     * @param xResolution The x resolution
     * @param yResolution The y resolution
     */
    Grid(long z, long width, long height, double xResolution, double yResolution) {
        this.z = z
        this.width = width
        this.height = height
        this.xResolution = xResolution
        this.yResolution = yResolution
        this.size = this.width * this.height
    }

**Comment by jericks** [comment]
Thanks for the detailed bug report!
