### ISSUE TITLE
Fromat.groovy: Format.getFormat is only taking a file object

### ISSUE THREAD

**Issue by gpotts** [geoscript/geoscript-groovy#16]
Hello,

In geotools core you can pass a generic object to find a format.  I have modified the code to allow for a generic object.  You do not have to limit the input to file only and you can actually pass an InputStream, URL, ... etc as an input for a particular format.

You might want to review the modification but all the tests seem to pass.  I have added bridges the original code by testing instanceof File so that your original file based if checks will still run.  With this modification you can now construct a new Format by a generic object.

    /**
     * Get the Format that can read the given File
     * @param file The File
     * @return A Format
     */
    static Format getFormat(Object input) {

        if(input instanceof File)
        {
            File file = input as File
            if (file.exists()) {
                AbstractGridFormat format = GridFormatFinder.findFormat(file);
                if (format == null || format instanceof UnknownFormat) {
                    return null
                }
                if (format instanceof GeoTiffFormat) {
                    return new GeoTIFF(file)
                } else if (format instanceof ArcGridFormat) {
                    return new ArcGrid(file)
                } else if (format instanceof GrassCoverageFormat) {
                    return new Grass(file)
                } else if (format instanceof GTopo30Format) {
                    return new GTopo30(file)
                } else if (format instanceof ImagePyramidFormat) {
                    return new ImagePyramid(file)
                } else if (format instanceof ImageMosaicFormat) {
                    return new Mosaic(file)
                } else if (format instanceof MrSIDFormat) {
                    return new MrSID(file)
                } else if (format instanceof WorldImageFormat) {
                    return new WorldImage(file)
                } else if (format instanceof NetCDFFormat) {
                    return new NetCDF(file)
                } else {
                    return new Format(format, file)
                }
            } else {
                String ext = file.name.substring(file.name.lastIndexOf(".") + 1).toLowerCase()
                if (ext in ["tif"]) {
                    return new GeoTIFF(file)
                } else if (ext in ["png","jpg","jpeg","gif"]) {
                    return new WorldImage(file)
                } else if (ext in ["arx"]) {
                    return new Grass(file)
                } else if (ext in ["sid"]) {
                    return new MrSID(file)
                } else if (ext in ["asc"]) {
                    return new ArcGrid(file)
                } else if (ext in ["nc"]) {
                    return new NetCDF(file)
                } else {
                    return null
                }
            }
        }
        else if(input instanceof InputStream)
        {
            AbstractGridFormat format = GridFormatFinder.findFormat(input);
            if (format == null || format instanceof UnknownFormat) {
                return null
            }else{
                return new Format(format, input)
            }
        }
    }

**Comment by gpotts** [comment]
Ooops made a mistalke.  Wanted the else to be less restrictive.

and allow all other object types to pass.  Removed the instance InputStream.

static Format getFormat(Object input) {

    if(input instanceof File)
    {
        File file = input as File
        if (file.exists()) {
            AbstractGridFormat format = GridFormatFinder.findFormat(file);
            if (format == null || format instanceof UnknownFormat) {
                return null
            }
            if (format instanceof GeoTiffFormat) {
                return new GeoTIFF(file)
            } else if (format instanceof ArcGridFormat) {
                return new ArcGrid(file)
            } else if (format instanceof GrassCoverageFormat) {
                return new Grass(file)
            } else if (format instanceof GTopo30Format) {
                return new GTopo30(file)
            } else if (format instanceof ImagePyramidFormat) {
                return new ImagePyramid(file)
            } else if (format instanceof ImageMosaicFormat) {
                return new Mosaic(file)
            } else if (format instanceof MrSIDFormat) {
                return new MrSID(file)
            } else if (format instanceof WorldImageFormat) {
                return new WorldImage(file)
            } else if (format instanceof NetCDFFormat) {
                return new NetCDF(file)
            } else {
                return new Format(format, file)
            }
        } else {
            String ext = file.name.substring(file.name.lastIndexOf(".") + 1).toLowerCase()
            if (ext in ["tif"]) {
                return new GeoTIFF(file)
            } else if (ext in ["png","jpg","jpeg","gif"]) {
                return new WorldImage(file)
            } else if (ext in ["arx"]) {
                return new Grass(file)
            } else if (ext in ["sid"]) {
                return new MrSID(file)
            } else if (ext in ["asc"]) {
                return new ArcGrid(file)
            } else if (ext in ["nc"]) {
                return new NetCDF(file)
            } else {
                return null
            }
        }
    }
    else
    {
        AbstractGridFormat format = GridFormatFinder.findFormat(input);
        if (format == null || format instanceof UnknownFormat) {
            return null
        }else{
            return new Format(format, input)
        }
    }
}

**Comment by jericks** [comment]
This looks like an excellent idea!  I will get this in soon (before we cut the 1.5 release).
