### ISSUE TITLE
The validation in TileCursor for z is not in synch with how the z is queried in Pyramid

### ISSUE THREAD

**Issue by gpotts** [geoscript/geoscript-groovy#17]
In the Method for Pyramid.groovy called grid(long z) it finds the z based on a comparison.  This gives support for having a sparse range that might just cover hypothetical levels  of 9-15.  In the TileCursor constructors the validate calls assumes that the z grids are always 0 based and always goes from 0..level-1 which is a contradiction to the code found in pyramid.

Attached is a fix that basically changes the occurrences of:

       this.z = validate(z, 0, tileLayer.pyramid.grids.size() - 1, "z")

To be:
        this.z = validate(z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")

and where z is not passed in the modification was:

            this.z = validate(m.z, 0, tileLayer.pyramid.grids.size() - 1, "z")

to be:
            this.z = validate(m.

z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")

Although this might be a problem too for the new validation supports pyramid definitions of any range it does not support still sparse sets.  For example,  only defining grid definitions for something like 4,8,9.

With the above fix we can define Grids with ranges of only 8-10 or 4-9 or whatever we want

I am not sure how to attache the update TileCursor.groovy file so the modifications are here (Just the constructors need modification that take a z):

    /**
     * Create TileCursor that iterates over every Tile in a given zoom level between the
     * given columns and rows
     * @param layer The TileLayer
     * @param z The zoom level
     * @param minX The min x or column
     * @param minY The min y or row
     * @param maxX The max x or column
     * @param maxY The max y or row
     */
    TileCursor (TileLayer layer, long z, long minX, long minY, long maxX, long maxY) {
        this.tileLayer = layer
       // this.z = validate(z, 0, tileLayer.pyramid.grids.size() - 1, "z")
        this.z = validate(z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")
        Grid grid = tileLayer.pyramid.grid(this.z)
        this.minX = validate(minX, 0, grid.width - 1, "minX")
        this.minY = validate(minY, 0, grid.height - 1, "minY")
        this.maxX = validate(maxX, 0, grid.width - 1, "maxX")
        this.maxY = validate(maxY, 0, grid.height - 1, "maxY")
        this.width = (maxX - minX) + 1
        this.height = (maxY - minY) + 1
        this.size = width * height
    }

    /**
     * Create TileCursor that iterates over every Tile in a given zoom level and within the given Bounds
     * @param layer The TileLayer
     * @param b The Bounds
     * @param z The zoom level
     */
    TileCursor(TileLayer layer, Bounds b, long z) {
        // Limit the Bounds to the intersection of the requested Bounds
        // and the Pyramid's Bounds
        Bounds pyramidBounds = layer.pyramid.bounds
        Bounds intersectedBounds = pyramidBounds.intersection(b)
        // Check that the intersected Bounds is not empty
        if (!intersectedBounds.empty) {
            Grid m = layer.pyramid.grid(z)
            Map tileCoords = layer.getTileCoordinates(intersectedBounds, m)
            this.tileLayer = layer
            //this.z = validate(z, 0, tileLayer.pyramid.grids.size() - 1, "z")
            this.z = validate(z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")
            Grid grid = tileLayer.pyramid.grid(this.z)
            this.minX = validate(tileCoords.minX, 0, grid.width - 1, "minX")
            this.minY = validate(tileCoords.minY, 0, grid.height - 1, "minY")
            this.maxX = validate(tileCoords.maxX, 0, grid.width - 1, "maxX")
            this.maxY = validate(tileCoords.maxY, 0, grid.height - 1, "maxY")
            this.width = (maxX - minX) + 1
            this.height = (maxY - minY) + 1
            this.size = width * height
        } else {
            // Cache the bounds as the empty Bounds with the correct projection
            this.bounds = intersectedBounds
            this.size = 0
        }
    }

    /**
     * Create TileCursor that iterates over every Tile within the given Bounds and for the x and y resolutions
     * @param layer The TileLayer
     * @param b The Bounds
     * @param resX The x resolution
     * @param resY The y resolution
     */
    TileCursor(TileLayer layer, Bounds b, double resX, double resY) {
        // Limit the Bounds to the intersection of the requested Bounds
        // and the Pyramid's Bounds
        Bounds pyramidBounds = layer.pyramid.bounds
        Bounds intersectedBounds = pyramidBounds.intersection(b)
        // Check that the intersected Bounds is not empty
        if (!intersectedBounds.empty) {
            Grid m = layer.pyramid.grid(intersectedBounds, resX, resY)
            Map tileCoords = layer.getTileCoordinates(intersectedBounds, m)
            this.tileLayer = layer
//            this.z = validate(m.z, 0, tileLayer.pyramid.grids.size() - 1, "z")
            this.z = validate(m.z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")
            Grid grid = tileLayer.pyramid.grid(this.z)
            this.minX = validate(tileCoords.minX, 0, grid.width - 1, "minX")
            this.minY = validate(tileCoords.minY, 0, grid.height - 1, "minY")
            this.maxX = validate(tileCoords.maxX, 0, grid.width - 1, "maxX")
            this.maxY = validate(tileCoords.maxY, 0, grid.height - 1, "maxY")
            this.width = (maxX - minX) + 1
            this.height = (maxY - minY) + 1
            this.size = width * height
        } else {
            // Cache the bounds as the empty Bounds with the correct projection
            this.bounds = intersectedBounds
            this.size = 0
        }
    }

    /**
     * Create TileCursor that iterates over every Tile within the Bounds for the image size
     * @param layer The TileLayer
     * @param b The Bounds
     * @param w The image width
     * @param h The image height
     */
    TileCursor(TileLayer layer, Bounds b, int w, int h) {
        // Limit the Bounds to the intersection of the requested Bounds
        // and the Pyramid's Bounds
        Bounds pyramidBounds = layer.pyramid.bounds
        Bounds intersectedBounds = pyramidBounds.intersection(b)
        // Check that the intersected Bounds is not empty
        if (!intersectedBounds.empty) {
            Grid m = layer.pyramid.grid(intersectedBounds, w, h)
            Map tileCoords = layer.getTileCoordinates(intersectedBounds, m)
            this.tileLayer = layer
//            this.z = validate(m.z, 0, tileLayer.pyramid.grids.size() - 1, "z")
            this.z = validate(m.z, tileLayer.pyramid.grids[0].z, tileLayer.pyramid.grids[-1].z, "z")
            Grid grid = tileLayer.pyramid.grid(this.z)
            this.minX = validate(tileCoords.minX, 0, grid.width - 1, "minX")
            this.minY = validate(tileCoords.minY, 0, grid.height - 1, "minY")
            this.maxX = validate(tileCoords.maxX, 0, grid.width - 1, "maxX")
            this.maxY = validate(tileCoords.maxY, 0, grid.height - 1, "maxY")
            this.width = (maxX - minX) + 1
            this.height = (maxY - minY) + 1
            this.size = width * height
        } else {
            // Cache the bounds as the empty Bounds with the correct projection
            this.bounds = intersectedBounds
            this.size = 0
        }
    }

**Comment by jericks** [comment]
Nice catch and excellent bug report!  Let me know if I missed any. 

Cheers,
Jared

**Comment by gpotts** [comment]
No problem.  The only thing though is that this fix assumes that grids[0] is the min z level and grids[-1] is the max Z value.  I guess a more generic way is to have a validator iterate through and see if z exists in the list but that would require another or a different validator to be implemented.  Didn't know if you wanted that or not.

**Comment by jericks** [comment]
Yep, that sounds like a good idea.  Would you mind creating a new issue?  Also, I would happily accept a pull request!

**Comment by gpotts** [comment]
will do.  I'll see which branch you are modifying and will fork it and issue a pull request.  Never done that before so I'll give it a shot.
