### ISSUE TITLE
TileCursor hasNext method.  Should it reset the cursor?

### ISSUE THREAD

**Issue by gpotts** [geoscript/geoscript-groovy#23]
In the TileCursor.groovy for hasNext:

    @Override
    boolean hasNext() {
        boolean hasNext = counter < size
        if (!hasNext) {
            reset()
        }
        hasNext
    }

I was wondering if this function is doing too much.  I think the caller should see if it hasNext and should always return false unless the caller calls reset.

I propose this method should be simplified to:

    @Override
    boolean hasNext() {
       counter < size
    }

What do you think.  

Take care

Garrett

**Comment by gpotts** [comment]
Hello All,  just curious if this is an issue.  If it is I will create a pull request

**Comment by jericks** [comment]
Hi Garrett!

Sorry this fell off my radar.  I can't remember why I made the cursor reset
itself but if it isn't causing problems I would like to leave it as is.

Thanks,
Jared

**Comment by gpotts** [comment]
Hello Jared:

No problem.  I had a workaround in my code to just store the boolean result and pop back out of the loop without calling hasNext a second time.

Thank you and take care

Garrett
