### ISSUE TITLE
Cannot resolve org.geoscript:geoscript-groovy:jar:1.3.1 from any maven repository

### ISSUE THREAD

**Issue by fgdrf** [geoscript/geoscript-groovy#25]
I tried boundless / osgeo repositories but cannot resolve it. When 1.3.1 came out distribution repository was set to http://repo.opengeo.org

Do we have a backup to add old releases to https://boundless.artifactoryonline.com/boundless/release/org/geoscript 
again?

**Comment by jericks** [comment]
Hey Frank!

Is this what you are looking for?

https://repo.boundlessgeo.com/main/org/geoscript/geoscript-groovy/1.3.1/

or

geoscript-groovy-1.3.1.jar
<https://repo.boundlessgeo.com/main/org/geoscript/geoscript-groovy/1.3.1/geoscript-groovy-1.3.1.jar>

Jared

**Comment by fgdrf** [comment]
Jared,

in uDig's pom was still the http url referenced instead of https. I fixed it and now downloads are fine.

Many thanks
