### ISSUE TITLE
GeoJSON decimal precision

### ISSUE THREAD

**Issue by akistanov** [geoscript/geoscript-groovy#26]
Currently GeoJSON  can be  created from Geometry with the help of  `org.geotools.geojson.geom.Geometry`JSON class. It is instantiated in `GeoJSONWriter `as `new GeometryJSON ()`. In this case `GeometryJSON` writes after dot only 4 decimal digits. It has sense to  use `new GeometryJSON (int decimals)` constructor to use precision up to user requirements.

**Comment by jericks** [comment]
Good idea, I am thinking about something like this:

GeoJSONWriter writer = new GeoJSONWriter()
Point p = new Point(111.123456,-47.234567)
writer.write(p, decimals: 6)
{"type":"Point","coordinates":[111.123456,-47.234567]}

**Comment by jericks** [comment]
Checkout https://github.com/geoscript/geoscript-groovy/commit/39648007d2b0704b4344a29bdf826eafd2ddd9b3
