### ISSUE TITLE
Why does a Feature's id change when its added to a Layer?

### ISSUE THREAD

**Issue by timkeane** [geoscript/geoscript-groovy#37]
https://github.com/timkeane/geoscript-test/blob/master/src/test/groovy/nyc/FeatureIdTest.groovy

```
package nyc

import spock.lang.*

import geoscript.feature.*
import geoscript.layer.Layer
import geoscript.geom.*

class ProximityTest extends Specification {

	def 'test that feature ids persist'(){
		given:
			Schema schema = new Schema('mySchema', [['geom', 'Point'], ['name', 'string'], ['address', 'string']])
			def attrs = [geom: new Point(1, 10), name: 'myName', address: 'myAddress']
			Feature inFeature = new Feature(attrs, 'myFID', schema)
			Layer layer = new Layer('myLayer', schema)
			layer.add(inFeature)
		when:
			Feature outFeature = layer.getFeatures()[0]
		then:
			inFeature.getId() == 'myFID' 
			inFeature.getId() == outFeature.getId() 
	}
}
```

**Comment by jericks** [comment]
The Feature ID is controlled by the Workspace (GeoTools DataStore).  The way you are creating Layers is actually using a Memory Workspace behind the scenes.  It creates ids like 'fid-4a2c8996_15b3b3e6f5b_-7ffc'.  If you use a Directory Workspace (which creates Shapefiles) you get an id like 'myLayer.1'.

The GeoTools docs have a good explanation:  http://docs.geotools.org/stable/userguide/library/data/featuresource.html (look for Handling of FeatureID).

I hope that helps.
