### ISSUE TITLE
Viewer.plot doesn't handle system.exit

### ISSUE THREAD

**Issue by moovida** [geoscript/geoscript-groovy#38]
While Plot.plot and Viewer.draw check for the "GroocyConsole" in the frame title, Viewer.plot does not. 

I assume (but am not sure) it is due to these lines:

https://github.com/geoscript/geoscript-groovy/blob/master/src/main/groovy/geoscript/plot/ViewerExtensionModule.groovy#L39-L44

**Comment by jericks** [comment]
Thanks!  I think I have a fix.  Does it look good to you? I tested an inline script, in the shell, and in the console.

geoscript-groovy -e "geoscript.viewer.Viewer.plot(new geoscript.geom.Point(1,1))"

geoscript-groovysh 
>>> geoscript.viewer.Viewer.plot(new geoscript.geom.Point(1,1))

geoscript-groovyConsole

geoscript.viewer.Viewer.plot(new geoscript.geom.Point(1,1))

**Comment by moovida** [comment]
Perfect, thanks!
