### ISSUE TITLE
Use Rule name with LegendItem

### ISSUE THREAD

**Issue by ebocher** [geoscript/geoscript-groovy#72]
The LegendItem built from a Layer, eg. legend.addLayer(layer) doesn't take into account the rule name but set the Filter Expression or the name of the Layer.  See https://github.com/geoscript/geoscript-groovy/blob/master/src/main/groovy/geoscript/carto/LegendItem.groovy#L243

So when a Legend is renderered with a set of rules it prints the filter expression e.g : VALUE = 0 ...

I propose to change a bit the code to set the rule to the LegendItem title.

```groovy
layer.style.gtStyle.featureTypeStyles().each { def fts ->
            fts.rules().each { def rule ->
                Filter filter = rule.filter
                String title=rule.name
                if(!title){
                 title = numberOfRules > 1 ? CQL.toCQL(filter) : layer.name.capitalize()
                }
                Style style = SLDStyle.fromRule(rule)
                if (legendEntryType == LegendEntryType.POINT) {
                    addPointEntry(title, style)
                } else if (legendEntryType == LegendEntryType.LINE) {
                    addLineEntry(title, style)
                }  else if (legendEntryType == LegendEntryType.POLYGON) {
                    addPolygonEntry(title, style)
                }
            }
        }
```
and the unit test
```groovy
  @Test
    void legendItemWithRuleName() {
        Workspace workspace = new Memory()
        Layer layer = workspace.create("points", [
                new Field("geom", "Point", "EPSG:4326"),
                new Field("id", "Integer")
        ])
        Shape symbolizer = new Shape("navy")
        def gtStyle = symbolizer.getGtStyle()
        gtStyle.featureTypeStyles()[0].rules()[0].name="Navy color"
        layer.style=new SLDReader.SLDStyle(gtStyle)
        LegendItem legend = new LegendItem(20, 20, 100, 100)
        legend.addLayer(layer)
        assertEquals("Navy color", legend.getEntries()[0].title)
}
```
Please find two images before and after this fix.

Before
![before](https://user-images.githubusercontent.com/1820572/186440327-ff308885-2f99-4e6e-b8c4-fb1d46275622.png)

After
![after](https://user-images.githubusercontent.com/1820572/186440369-6a21af36-0d50-469f-9246-dcf77ce31d42.png)

**Comment by ebocher** [comment]
By the way, it'd be nice to 

- [ ] add a method on Symbolizer to set a Name

Something like that 

```groovy
Shape symbolizer = new Shape("navy").name("Hospital")
```

- [ ] update the UniqueValues method to set only the value and not the whole filter to the LegendEntry

**Comment by jericks** [comment]
I think this is a really good idea and worth pursuing. 

1. Adding name to Symbolizer creates a conflict with an existing name property on the Hatch class.  I generally try to avoid breaking changes but renaming the Hatch's name to something like pattern would be doable.
2. If we had a Composite which is made up to one or more Symbolizers which all had names what would the name of the Composite be?
`Composite symbolizer = new Fill("red").name("Fill") + new Stroke("#ffffff").name("Stroke") `
Should we use the last name (so it would be "Stroke")?

Your example map and legend look great  by the way.

**Comment by ebocher** [comment]
> 1. Adding name to Symbolizer creates a conflict with an existing name property on the Hatch class.  I generally try to avoid breaking changes but renaming the Hatch's name to something like pattern would be doable.

It will be nice ;-)


> 2\. If we had a Composite which is made up to one or more Symbolizers which all had names what would the name of the Composite be?
>     `Composite symbolizer = new Fill("red").name("Fill") + new Stroke("#ffffff").name("Stroke") `
>     Should we use the last name (so it would be "Stroke")?

humm you are right. GeoScript introduces its own Symbolizer model where a Composite is also a Symbolizer and contains a set of Symbolizers. In fact, each element Fill, Stroke is a Symbolizer. It's comfortable to write something like this : 
```
Symbolizer symbolizer = new Fill("red") + new Stroke("#ffffff")
```
but causes some potential modelling issues
```
new Fill("red") + new Stroke("#ffffff")
```

is transformed in two symbolizers (Polygon and Line) awhereas we could expect here only a polygonsymbolizer.

This will affect the effect and the rendering time (two passes instead of one).

Maybe a solution would be to allow this kind of syntax : 
```
new Fill("red") << new Stroke("#ffffff")
```

but new problems will arise if the elements have two different filters

Best regards

**Comment by jericks** [comment]
Take a look at https://github.com/geoscript/geoscript-groovy/pull/75 when you get a chance.

**Comment by ebocher** [comment]
Do you have any plan in mind about a PolygonSymbolizer with a fill +  stroke ?
thanks

**Comment by jericks** [comment]
I don't.  When the project designed the style apis years ago, we compared a more GeoTools / OpenLayers like api with the more composable one that we ended up with.  I don't see a way to fix the api without breaking backwards compatibility.  But, I am complete open to ideas and pull requests.

**Comment by ebocher** [comment]
Thanks a lot. I'll think about it a bit ;-)
