### ISSUE TITLE
ScaleBarItem border properties

### ISSUE THREAD

**Issue by ebocher** [geoscript/geoscript-groovy#73]
The ScaleBarItem shares the same information to custom the color and the size of stroke for the border (rectangle) and line of the scale bar. 
It would be nice to split them. Something like this 
- borderColor
- borderWidth
- backGroundColor
- barWidth
- barColor

The user will be able to control  each element and build for example a scalebar with a background color but without a border around the scale.

See an example

![map](https://user-images.githubusercontent.com/1820572/188446562-ff0499fd-5ddb-4edb-85f5-f9d21490165f.png)

**Comment by jericks** [comment]
Take a look at https://github.com/geoscript/geoscript-groovy/pull/76 when you get a chance.

**Comment by ebocher** [comment]
Excellent !
